# Generated by Django 5.1.5 on 2025-02-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quick_first_aid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickfirstaid',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
    ]
