# Generated by Django 5.1.7 on 2025-04-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='landslideprediction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='landslideprediction',
            name='created_at',
        ),
    ]
